-- =======================================================
-- StudyPulse AI PSMS — Oracle SQL Database DDL Schema
-- Compatible with Oracle 11g, 12c, 19c, 21c, 23c / XE
-- =======================================================

-- 1. USERS TABLE
CREATE TABLE PSMS_USERS (
  ID VARCHAR2(50) PRIMARY KEY,
  USERNAME VARCHAR2(100) NOT NULL UNIQUE,
  EMAIL VARCHAR2(150) NOT NULL,
  PHONE VARCHAR2(20),
  PASSWORD VARCHAR2(255) NOT NULL,
  USER_ID VARCHAR2(50),
  PROFILE_IMAGE VARCHAR2(500),
  SETTINGS CLOB,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. MENTORS TABLE
CREATE TABLE PSMS_MENTORS (
  ID VARCHAR2(50) PRIMARY KEY,
  NAME VARCHAR2(150) NOT NULL,
  PHONE VARCHAR2(20),
  EMAIL VARCHAR2(150) NOT NULL,
  MENTOR_ROLL_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
  DEPARTMENT VARCHAR2(50),
  STATUS VARCHAR2(30) DEFAULT 'Active',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. TEAMS TABLE
CREATE TABLE PSMS_TEAMS (
  ID VARCHAR2(50) PRIMARY KEY,
  TEAM_BATCH NUMBER NOT NULL,
  TEAM_NAME VARCHAR2(150) NOT NULL,
  STUDENT1_REGISTER_NUMBER NUMBER NOT NULL,
  STUDENT2_REGISTER_NUMBER NUMBER NOT NULL,
  PROJECT_TITLE VARCHAR2(255),
  MENTOR_ROLL_NUMBER VARCHAR2(50),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. STUDENTS TABLE
CREATE TABLE PSMS_STUDENTS (
  ID VARCHAR2(50) PRIMARY KEY,
  NAME VARCHAR2(150) NOT NULL,
  ROLL_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
  REGISTER_NUMBER NUMBER NOT NULL UNIQUE,
  PHONE VARCHAR2(20),
  CLASS VARCHAR2(10),
  YEAR VARCHAR2(10),
  DEPARTMENT VARCHAR2(50),
  EMAIL VARCHAR2(150),
  PHOTO VARCHAR2(500),
  MENTOR_ROLL_NUMBER VARCHAR2(50),
  TEAM_NUMBER NUMBER DEFAULT 1,
  TEAM_NAME VARCHAR2(150),
  BATCH_NUMBER NUMBER DEFAULT 35,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_STUDENT_MENTOR FOREIGN KEY (MENTOR_ROLL_NUMBER) REFERENCES PSMS_MENTORS(MENTOR_ROLL_NUMBER) ON DELETE SET NULL
);

-- 5. PROJECTS TABLE
CREATE TABLE PSMS_PROJECTS (
  ID VARCHAR2(50) PRIMARY KEY,
  PROJECT_TITLE VARCHAR2(255) NOT NULL,
  DESCRIPTION VARCHAR2(1000),
  OBJECTIVE VARCHAR2(1000),
  TECH_STACK VARCHAR2(255),
  EXTERNAL_EVENT_SUBMITTED NUMBER(1) DEFAULT 0,
  ACCEPTED_PROJECT NUMBER(1) DEFAULT 0,
  EXTERNAL_DEMO_OR_PAPER NUMBER(1) DEFAULT 0,
  PUBLISHED NUMBER(1) DEFAULT 0,
  PATENT_GRANTED NUMBER(1) DEFAULT 0,
  BATCH_NUMBER NUMBER NOT NULL UNIQUE,
  MENTOR_ROLL_NUMBER VARCHAR2(50),
  STUDENT1_REGISTER_NUMBER NUMBER,
  STUDENT2_REGISTER_NUMBER NUMBER,
  PROJECT_STATUS VARCHAR2(50) DEFAULT 'In Progress',
  PUBLICATION_STATUS VARCHAR2(50) DEFAULT 'Submitted',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. REVIEWS TABLE (Reviews 1 to 6 per student)
CREATE TABLE PSMS_REVIEWS (
  ID VARCHAR2(50) PRIMARY KEY,
  REVIEW_NUMBER NUMBER NOT NULL,
  BATCH_NUMBER NUMBER NOT NULL,
  STUDENT_REGISTER_NUMBER NUMBER NOT NULL,
  PROJECT_TITLE VARCHAR2(255),
  PROJECT_STATUS VARCHAR2(50),
  REVIEW_STATUS VARCHAR2(50) DEFAULT 'Not Completed',
  MARK NUMBER DEFAULT 0,
  MAX_MARK NUMBER DEFAULT 10,
  COMPLETED NUMBER(1) DEFAULT 0,
  REVIEW_DATE VARCHAR2(30),
  COMMENTS VARCHAR2(1000),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. NOTIFICATIONS TABLE
CREATE TABLE PSMS_NOTIFICATIONS (
  ID VARCHAR2(50) PRIMARY KEY,
  TITLE VARCHAR2(255) NOT NULL,
  MESSAGE VARCHAR2(1000) NOT NULL,
  NOTIFICATION_DATE VARCHAR2(50),
  IS_READ NUMBER(1) DEFAULT 0,
  NOTIFICATION_TYPE VARCHAR2(50) DEFAULT 'review',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. ASYNC TASK QUEUE TABLE
CREATE TABLE PSMS_QUEUE_TASKS (
  ID VARCHAR2(50) PRIMARY KEY,
  TASK_TYPE VARCHAR2(50) NOT NULL,
  PAYLOAD CLOB NOT NULL,
  STATUS VARCHAR2(30) DEFAULT 'PENDING',
  ATTEMPTS NUMBER DEFAULT 0,
  MAX_ATTEMPTS NUMBER DEFAULT 3,
  ERROR_MESSAGE VARCHAR2(1000),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PROCESSED_AT TIMESTAMP
);

-- Create Indexes for Query Optimization
CREATE INDEX IDX_STUDENT_REGNO ON PSMS_STUDENTS(REGISTER_NUMBER);
CREATE INDEX IDX_PROJECT_BATCH ON PSMS_PROJECTS(BATCH_NUMBER);
CREATE INDEX IDX_REVIEW_STUDENT ON PSMS_REVIEWS(STUDENT_REGISTER_NUMBER);
CREATE INDEX IDX_REVIEW_NUM ON PSMS_REVIEWS(REVIEW_NUMBER);
CREATE INDEX IDX_QUEUE_STATUS ON PSMS_QUEUE_TASKS(STATUS);
